server:
  port: 9526
  readTimeOut: 40
app:
  mode: release #gin的启动模式， debug or release or test
  log_path: ./logs
mysql:
  default:
    driver: mysql
    maxOpenCon: 10
    maxIdleCon: 5
    maxIdleLifeTime: 5
    maxLifeTime: 10
    master:
      userName: xxxx
      password: xxxx
      host: xx.xx.xx.xx
      port: 3306
      dbName: gspider
      charset: utf8mb4
    slave:
      - userName: xxxx
        password: xxxx
        host: xx.xx.xx.xx
        port: 3306
        dbName: gspider
        charset: utf8mb4
redis: # 可配置多个redis，但实例名称不可一致
  default: # 实例名称 test_cache
    driver: replication #主从复制
    master: xx.xx.xx.xx:6379
    slaves: xx.xx.xx.xx:6379 # 多个用,分割
    password: xxxx
    readonlyPassword: xxxx
    options:
      db: 0 # 使用哪个db
      poolsize: 20 # 连接池保持的最大连接数，默认每个cpu保持10
      dialtimeout: 1s # 连接超时，默认5s
      readtimeout: 10s # socket读超时，默认3s
      writetimeout: 10s # socket写超时，默认readTimeout
